Sync upstream worker code
litentry/litentry-parachain pull request #1165
Opened 2023-01-09 14:16 UTC by Chengcheng-S

Daily work 
Sync upstream worker code

2023-01-09 18:58 UTC, Kailai-Wang requested changes
We are **at least** missing this part: https://github.com/integritee-network/worker/commit/98e151adbb83d49c9f1204d23520fc71620d8c71#diff-b45d7f9d388a23fd97f42304612c00c9ea1205f05fc1e8bcc41439effa02406bR106-R125

We need to be more careful when merging and resolving the conflicts, maybe ask in the channel if we are unsure which part to keep.

2023-01-09 23:35 UTC, BillyWooo requested changes
Except the comment from Kai, please take `core-primitives/stf-executor/Cargo.toml` from upstream to avoid conflict in the future.

2023-01-10 01:20 UTC, Chengcheng-S commented
> We are **at least** missing this part: [integritee-network/worker@98e151a#diff-b45d7f9d388a23fd97f42304612c00c9ea1205f05fc1e8bcc41439effa02406bR106-R125](https://github.com/integritee-network/worker/commit/98e151adbb83d49c9f1204d23520fc71620d8c71#diff-b45d7f9d388a23fd97f42304612c00c9ea1205f05fc1e8bcc41439effa02406bR106-R125)
> 
> We need to be more careful when merging and resolving the conflicts, maybe ask in the channel if we are unsure which part to keep.

okay got it

2023-01-10 10:17 UTC, Kailai-Wang approved these changes

2023-01-10 11:28 UTC, BillyWooo approved these changes

2023-01-10 12:59 UTC, merged