add main litentry address into IDGraph
litentry/litentry-parachain pull request #1394
Opened 2023-03-02 15:57 UTC by BillyWooo

Add one special item when main litentry account not existed. 

Resolved #1174 

```
if IDGraphs::<T>::get(&who, &prime_id).is_none() {
    // Not existed, so create the prime entry.
    let context = IdentityContext::<T> {
	    metadata: None,
	    creation_request_block: Some(0),
	    verification_request_block: Some(0),
	    is_verified: false,
    };
    IDGraphs::<T>::insert(&who, &prime_id, context);
}
```

2023-03-02 19:58 UTC, Kailai-Wang reviewed
Thanks. I think we still miss a few things:
- IMP mock needs to be adjusted
- we should disallow deletion of prime_identity in `remove_identity`
- same applies to `verify_identity` => we might need an error like `IdentityAlreadyVerified`
- ts-tests should test about the size and content of the ID-graph (to make sure we do have the prime id)

2023-03-02 19:58 UTC, Kailai-Wang commented on tee-worker/litentry/pallets/identity-management/src/lib.rs
> +					is_verified: false,
I think `is_verified` should be true

2023-03-06 04:02 UTC, jingleizhang requested changes
Please add a case in ts-test, to cover the `RemovePrimeIdentityDisallowed` error. Thanks!

2023-03-07 10:54 UTC, jingleizhang approved these changes

2023-03-09 09:22 UTC, jingleizhang commented
According to failed CI log, there is a panic:

> [2023-03-08T15:17:42Z DEBUG itc_parentchain_indirect_calls_executor] Scanning block 77 for relevant xt
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { cause: None, desc: "Not enough data to decode vector" }', /root/work/tee-worker/core/parentchain/indirect-calls-executor/src/executor/litentry/batch_all.rs:343:81
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
             at library/core/src/panicking.rs:65
   2: core::result::unwrap_failed
             at library/core/src/result.rs:1791
   3: <core::slice::iter::IterMut<T> as core::iter::traits::iterator::Iterator>::for_each
   4: <E as itc_parentchain_indirect_calls_executor::executor::DecorateExecutor<ShieldingKeyRepository,StfEnclaveSigner,TopPoolAuthor,NodeMetadataProvider>>::decode_and_execute
   5: <itc_parentchain_indirect_calls_executor::IndirectCallsExecutor<ShieldingKeyRepository,StfEnclaveSigner,TopPoolAuthor,NodeMetadataProvider> as itc_parentchain_indirect_calls_executor::ExecuteIndirectCalls>::execute_indirect_calls_in_extrinsics
   6: <itc_parentchain_block_importer::block_importer::ParentchainBlockImporter<ParentchainBlock,ValidatorAccessor,StfExecutor,ExtrinsicsFactory,IndirectCallsExecutor> as itc_parentchain_block_importer::ImportParentchainBlocks>::import_parentchain_blocks
   7: <itc_parentchain_block_import_dispatcher::triggered_dispatcher::TriggeredDispatcher<BlockImporter,BlockImportQueue> as itc_parentchain_block_import_dispatcher::triggered_dispatcher::TriggerParentchainBlockImport>::import_until
   8: <T as its_consensus_slots::PerShardSlotWorkerScheduler<ParentchainBlock>>::on_slot
   9: execute_trusted_calls
  10: sgx_execute_trusted_calls
  11: do_ecall
  12: enter_enclave
  13: <unknown>
  14: <unknown>
note: Some details are omitted, call backtrace::enable_backtrace() with 'PrintFormat::Full' for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5

2023-03-10 06:00 UTC, jingleizhang requested changes
please fix the panic bug

2023-03-14 07:39 UTC, BillyWooo commented
> please fix the panic bug
The panic bug was introduced by a merge from other branch. It's already fixed there and merged back.

2023-03-14 08:59 UTC, jingleizhang approved these changes

2023-03-14 11:21 UTC, merged

2023-03-14 15:26 UTC, Kailai-Wang reviewed
A few hiccups I found

2023-03-14 15:26 UTC, Kailai-Wang commented on tee-worker/litentry/pallets/identity-management/src/lib.rs
> +				network: SubstrateNetwork::Litentry,
This won't work if we are on other mainnets (e.g. rococo)

The network has to be created from `parent_ss58_prefix` - alternatively we can still hardcode it but need to change it before we deploy on other chains

2023-03-14 15:26 UTC, Kailai-Wang commented on tee-worker/litentry/pallets/identity-management/src/lib.rs
> +
I think this should be extended to non-prime Identities as well - we should quite early if it's already verified.

2023-03-14 15:26 UTC, Kailai-Wang commented on tee-worker/litentry/pallets/identity-management/src/lib.rs
> +			let prime_user_address: Address32 = prime_address_raw.into();
Can't we directly compare `prime_id` and `identity`?

2023-03-14 15:26 UTC, Kailai-Wang commented on tee-worker/litentry/pallets/identity-management/src/lib.rs
> +
Same as above - I think it's enough to check if `identity` is `prime_id`