Check mrenclave and scheduled height before produce blocks(fix #1295)
litentry/litentry-parachain pull request #1416
Opened 2023-03-07 01:01 UTC by DogLi

1. after sidechain import block, set the block suspender if `block_height >= scheduled block height`
2. if `block_height == scheduled block height`, migration

2023-03-12 13:33 UTC, Kailai-Wang commented
Looks like the TEE tests failed.

2023-03-15 09:34 UTC, jingleizhang commented
I have no idea why this PR was closed...

2023-03-15 09:42 UTC, Kailai-Wang commented
Yea this PR https://github.com/litentry/litentry-parachain/pull/1462 wasn't linked to any issue.

**It's always a good practice to link the issue that will be fixed by a PR**

2023-03-16 23:06 UTC, Kailai-Wang requested changes
I didn't go very details - only skimmed through the logic in `tee-worker/sidechain/consensus/aura/src/block_importer.rs`.

I'm not sure why the check logic happens inside a block importer rather than the block proposer. Maybe the argument is we need to import all missing blocks before producing a block but I'm not sure if there's any subtle synchronisation issue. 

The scheduled enclave is something we get from parentchain syncing, not from sidechain state. In that sense I think we don't have to rely on the (imported) sidechain block to do this.

Additionally, is `get_next_scheduled_enclave` correctly implemented?
I think we need such functionality, given a sidechain_block_number, the function should return the expected MRENCALVE. For example, by syncing the parentchain blocks we know that:

|sidechain_block_number|expected_MRENCLAVE|
|-|-|
|0|A|
|20|B|
|25|C|

so:
for input 19 - it should return A => It means we are going to generate block number 19 and we have to check if our MRENCLAVE is equal to A
for input 20 -> it should return B
for input 26 -> it should return C

and so on.

2023-03-16 23:06 UTC, Kailai-Wang commented on tee-worker/sidechain/consensus/common/src/block_production_suspension.rs
> +	fn resume_for_production(&self) -> Result<()>;
I like the original names TBH 😂 
The trait is already with the name `..Production`, so I'm OK if the member function doesn't have a `production` keyword.

I'm fine with just `suspend_for_sync` and `resume` - if you think `suspend_for_sync` is inaccurate, we could simply use `suspend`

2023-03-16 23:06 UTC, Kailai-Wang commented on tee-worker/sidechain/consensus/aura/src/block_importer.rs
> +						.suspend_for_production()
It's suspended here but I don't find any place where it gets resumed, is that correct?

2023-03-16 23:06 UTC, Kailai-Wang commented on tee-worker/sidechain/consensus/aura/src/block_importer.rs
> +		let block_number = sidechain_block.block().header().block_number();
the `sidechain_block.block()` is the sidechain block that is going to be imported - I find it questionable: I thought it should be the block that is going to be produced.

Or more in general: why put the logic in `verify_import`?

2023-03-16 23:06 UTC, Kailai-Wang commented on tee-worker/sidechain/consensus/aura/src/block_importer.rs
> +				if scheduled_block_number <= block_number {
This if-condition is always false if I'm not mistaken.

The `scheduled_block_number` is calculated from `get_next_scheduled_enclave` where the returned block number is greater than the `block_number`:
```
		self.scheduled_enclaves
			.iter()
			.filter_map(
				|(k, v)| {
					if k > &current_side_chain_number {
						Some(v.clone())
					} else {
						None
					}
				},
```

2023-03-16 23:06 UTC, Kailai-Wang commented on tee-worker/sidechain/consensus/aura/src/block_importer.rs
> +				if scheduled_block_number == block_number {
As mentioned above, we probably will never go into this branch.

2023-03-16 23:07 UTC, Kailai-Wang commented
And yes - having a feature branch in the same repo would be beneficial for the reviewers to check the code locally :)

2023-04-06 20:37 UTC, Kailai-Wang commented
Superseded by #1579

2023-04-06 20:37 UTC, closed without merging