Add public getter of account nouce
litentry/litentry-parachain pull request #1729
Opened 2023-05-24 04:46 UTC by zhouhuitian

resolved #1710

2023-05-25 08:41 UTC, BillyWooo approved these changes
LGTM

2023-05-25 19:52 UTC, Kailai-Wang requested changes
Thank you!

I think the implementation part is OK, but maybe it's not worth a dedicated test, as you probably need to use it anyway in the ts-test.

So can you please:
- remove the test and CLI 
- remove the nonce from trusted getter (also from ts-test definitions)
- (optional) modify the demo-code of DI to use this getter to retrieve nonce instead of hardcoding

2023-05-29 12:23 UTC, Kailai-Wang commented
Thank you, the logic looks good.

I'll approve it first, the changes in ts-test can be done in a follow-up PR

2023-05-29 12:25 UTC, Kailai-Wang approved these changes

2023-05-29 12:25 UTC, merged