Ring constant
litentry/litentry-parachain pull request #1768
Opened 2023-06-11 12:58 UTC by songzhouran

2023-06-11 13:09 UTC, songzhouran commented
close #1766

2023-06-12 01:35 UTC, songzhouran commented
No alternative for USER_SHIELDING_KEY_LEN = 32;
There are constants about key_len:
ring::aead::chacha20_poly1305_openssh::KEY_LEN = 64 and ring::aead::chacha::KEY_LEN = 32 is private.

2023-06-19 02:45 UTC, Kailai-Wang requested changes

2023-06-19 02:45 UTC, Kailai-Wang commented on primitives/core/Cargo.toml
> +ring = { git = "https://github.com/Niederb/ring-xous.git", branch = "0.16.20-cleanup", default-features = false, features = ["alloc"] }
any reason not to use the standard `ring`?

2023-06-19 02:45 UTC, Kailai-Wang commented on tee-worker/litentry/primitives/src/aes.rs
> +use ring::aead::NONCE_LEN;
You probably want to expose it in `primitives/core/src/key.rs` and import it in this crate and `use` it from the crate, similar to e.g. `AesOutput`

2023-06-20 07:51 UTC, Kailai-Wang commented
Sorry, I believe for primitives/core we'd still need a no-std version of `ring` (e.g. `ring-xous`) as it's used in wasm too, see the old problem that we met: https://github.com/litentry/litentry-parachain/issues/963#issuecomment-1325701638

2023-06-20 08:21 UTC, Kailai-Wang reviewed
One small thing

2023-06-20 08:21 UTC, Kailai-Wang commented on tee-worker/litentry/primitives/src/aes.rs
> +use crate::{AesOutput, UserShieldingKeyNonceType, UserShieldingKeyType};
These can be merged

2023-06-20 08:35 UTC, Kailai-Wang approved these changes

2023-06-20 10:15 UTC, merged