Fee related part 1
litentry/litentry-parachain pull request #188
Opened 2021-10-27 08:44 UTC by wangminqi

-relocate pallet-payment-interface into parachain/pallets
-implement pallet-payment-interface in parachain runtime

2021-10-27 08:45 UTC, wangminqi commented
Wait for CI improvement

2021-10-28 14:46 UTC, Satoshi-Kusumoto requested changes

2021-10-28 14:46 UTC, Satoshi-Kusumoto commented on node/src/chain_spec.rs
> +				)],
better not to change

2021-10-28 14:46 UTC, Satoshi-Kusumoto commented on node/src/command.rs
> +		                                                                         * prod.json */
ditto

2021-10-28 14:46 UTC, Satoshi-Kusumoto commented on node/src/command.rs
> +		},
You runned fmt?

2021-10-28 14:46 UTC, Satoshi-Kusumoto commented on pallets/payment-interface/Cargo.toml
> +pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false }
order

2021-10-28 14:46 UTC, Satoshi-Kusumoto commented on pallets/payment-interface/Cargo.toml
> +	"pallet-balances/std",
ditto

2021-10-28 14:46 UTC, Satoshi-Kusumoto commented on runtime/src/lib.rs
> +
This should be token related

2021-10-28 14:46 UTC, Satoshi-Kusumoto commented on pallets/payment-interface/src/lib.rs
> +		RatioOf { treasury: 0, author: 0, burned: 1 }
Better to use 100 and write in documentation that recommendation is to set it sum up to 100
Also set initial value to treasury = 100

2021-10-28 14:46 UTC, Satoshi-Kusumoto commented on pallets/payment-interface/src/lib.rs
> +	pub type FixBlockReward<T: Config> = StorageValue<_, u32, ValueQuery>;
Next time should not have it here

2021-10-28 14:46 UTC, Satoshi-Kusumoto commented on pallets/payment-interface/src/lib.rs
> +		#[pallet::weight(10)]
Pls put weight related todos

2021-10-28 14:46 UTC, Satoshi-Kusumoto commented on pallets/payment-interface/src/lib.rs
> +			}
As discussed don't need this

2021-10-28 14:46 UTC, Satoshi-Kusumoto commented on pallets/payment-interface/src/lib.rs
> +	// use codec::Encode;
???

2021-10-29 02:22 UTC, wangminqi commented on node/src/command.rs
> +		},
yes. eeee. Should I?

2021-10-29 02:24 UTC, wangminqi commented on node/src/chain_spec.rs
> +				)],
I think fmt does this change.

2021-10-29 02:24 UTC, wangminqi commented on node/src/command.rs
> +		                                                                         * prod.json */
fmt effect.

2021-10-29 02:40 UTC, wangminqi commented on node/src/command.rs
> +		},
This is fmt's change.

2021-10-29 07:32 UTC, closed without merging