[WIP] fix: remove SubstrateTestNet
litentry/litentry-parachain pull request #1954
Opened 2023-07-27 13:48 UTC by felixfaisal

Resolves #1918

2023-07-27 20:05 UTC, kziemianek requested changes
I think you need to remove occurence of this variant from other files too.

For example it is used in di examples 
https://github.com/litentry/litentry-parachain/blob/055b19d358089b0ed2f9571a23badbd82c638f6d/tee-worker/ts-tests/integration-tests/examples/direct-invocation/example.ts#L366

I think you should get chain metadata and rebuild ts types too.

2023-07-31 07:12 UTC, Verin1005 commented
>For example it is used in di examples

see [code](https://github.com/litentry/litentry-parachain/blob/dev/tee-worker/ts-tests/integration-tests/examples/direct-invocation/example.ts#L366)

2023-07-31 09:54 UTC, Kailai-Wang reviewed
And yes there should be more places where this network is used

2023-07-31 09:54 UTC, Kailai-Wang commented on primitives/core/src/network.rs
> +	Polkadot = 0,
Does the integer assignment bring anything? It's encoded by SCALE anyway

2023-07-31 16:18 UTC, grumpygreenguy commented on primitives/core/src/network.rs
> +	Polkadot = 0,
I take it the intent here is to preserve the SCALE encoding by keeping the integer value unchanged; not sure if that's something we want to mess with / rely on.

2023-08-04 07:56 UTC, kziemianek commented on primitives/core/src/network.rs
> +	Polkadot = 0,
I think yes, and we should try to apply `    #[codec(index = 15)]` to all enums in api contract definitions.

2023-08-07 09:19 UTC, felixfaisal commented
I will be closing this PR for now, because i don't want to poke around with `TS` code without understanding it atleast partially if not fully. As this is a low priority issues, it should be fine for now.

2023-08-07 09:19 UTC, closed without merging