di test
litentry/litentry-parachain pull request #2022
Opened 2023-08-14 17:58 UTC by songzhouran

### Context

resolves #1987

2023-08-16 14:04 UTC, arieljbirnbaum requested changes

2023-08-16 14:04 UTC, grumpygreenguy commented on tee-worker/docker/lit-substrate-di-test.yml
> +      "bash -c '/usr/local/worker-cli/lit_ts_test.sh substrate-di-examples 2>&1' "
This won't work if `substrate-di-examples:staging` isn't defined (and configured with the right `.env` file, etc) in `tee-worker/ts-tests/integration-tests/package.json`.

Not sure if it's worth to add this tbh; the `identity` test suite has already been ported and the `vc` one is [underway](https://github.com/litentry/litentry-parachain/pull/1956); these examples [should become redundant](https://github.com/litentry/litentry-parachain/issues/1987#issuecomment-1665735488) then.

2023-08-16 20:48 UTC, kziemianek commented
As Kai suggested in issue, let's wait for direct invocation full tests and remove examples so we don't need to care about them anymore.

2023-09-06 07:07 UTC, kziemianek commented
Hi @songzhouran what do you think about closing this PR and opening another one with examples removal ?

2023-09-06 23:27 UTC, songzhouran commented
@kziemianek I remove code in this PR. Do we need to open another PR?

2023-09-07 05:24 UTC, kziemianek approved these changes

2023-09-07 05:24 UTC, kziemianek commented
> @kziemianek I remove code in this PR. Do we need to open another PR?

No, it's fine. 👍🏼

2023-09-07 15:30 UTC, grumpygreenguy approved these changes
Kill it with fire :raised_hands: :fire:

2023-09-07 17:14 UTC, merged