Unify the signature error when verifying web3 identities #2033
litentry/litentry-parachain pull request #2038
Opened 2023-08-17 23:39 UTC by songzhouran

### Context
fix #2033

2023-08-18 05:42 UTC, BillyWooo approved these changes
LGTM

2023-08-18 06:39 UTC, kziemianek commented
Looks like a breaking change to me, isn't it ?

2023-08-18 06:41 UTC, kziemianek requested changes

2023-08-18 06:41 UTC, kziemianek commented on tee-worker/app-libs/stf/src/helpers.rs
>  	//       will merge it to `VerifyWeb3SignatureFailed` after the campaign
I think you can remove this comment ?

2023-08-18 06:49 UTC, Kailai-Wang requested changes
You'd need to regenerate the metadata and types:
in the `tee-worker/ts-tests` run: `corepack yarn update-build`

2023-08-18 06:49 UTC, Kailai-Wang commented on primitives/core/src/error.rs
> +	VerifyWeb3SignatureFailed,
You need to regenerate the metadata for sure

2023-08-18 06:49 UTC, Kailai-Wang commented on tee-worker/app-libs/stf/src/helpers.rs
> +		return Err(StfError::LinkIdentityFailed(ErrorDetail::VerifyWeb3SignatureFailed))
I prefer using `ensure!`

2023-08-22 10:20 UTC, kziemianek approved these changes

2023-08-23 17:42 UTC, Kailai-Wang approved these changes

2023-08-23 17:42 UTC, merged