build
litentry/litentry-parachain pull request #2134
Opened 2023-09-14 15:37 UTC by songzhouran

### Context

### Labels

Please apply following PR-related labels when appropriate:
- `C0-breaking`: if your change could break the existing client, e.g. API change, critical logic change 
- `C1-noteworthy`: if your change is non-breaking, but is still worth noticing for the client, e.g. reference code improvement

### How (Optional)

### Testing Evidences

Please attach any relevent evidences if applicable

2023-09-18 14:18 UTC, Kailai-Wang commented
I'd suggest that you add more details to this PR, as we can't infer any by just looking at the PR itself:
- the title is `build`, all historical commits are `build` too
- the PR description doesn't contain much information
- it's not linked to any issue

That's a bad example of PR if I'm frank :(

2023-09-21 09:48 UTC, Kailai-Wang requested changes
I think `runs-on` images in yml are irrelevant. We only care about the final image of our parachain for now

2023-09-21 09:48 UTC, Kailai-Wang commented on .github/workflows/benchmark-runtime-weights.yml
I don't think you need to change the `runner-os` for GHA - it should be irrelevant

2023-09-21 09:48 UTC, Kailai-Wang commented on docker/Dockerfile
> +FROM rust:1.68 as builder
Any reason for it?

2023-09-21 09:48 UTC, Kailai-Wang commented on docker/Dockerfile
> +RUN strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
Is it only for debugging purpose?

2023-09-25 07:07 UTC, wangminqi commented
Currently T40 is Ubuntu 22.04.
I am not sure if the solution to Ubuntu 20 as base image is a good idea.
As a matter of fact, bump to Ubuntu 22.04 from 18 is made by me for solving GLIBC not found issue in the first place.

2023-09-27 22:00 UTC, kziemianek commented on docker/Dockerfile
> +RUN echo "deb http://th.archive.ubuntu.com/ubuntu jammy main" >> /etc/apt/sources.list
jammy is 22 while it's operating on 20. I'm not sure if it's a good idea to mix repos from various versions.

2023-09-27 23:31 UTC, Kailai-Wang commented on docker/Dockerfile
One thing to check is if this line is still valid:
```
FROM rust:latest as builder
```

As it defines the building environment for the parachain binary - if the parachain binary is built against ubuntu 22 (and thus a newer version of glibc), then no wonder it won't work under ubuntu 20 

It can be verified by executing `make launch-docker-rococo` on a ubuntu 20 host

2023-09-27 23:34 UTC, Kailai-Wang commented
I see this: https://github.com/litentry/litentry-parachain/actions/runs/6331837822/job/17197287030

so most likely the `rust:latest` isn't the right image anymore (= it's based on ubuntu 22 too)

2023-09-28 03:55 UTC, songzhouran commented
I tried to print ubuntu version in rust 1.20 image, found it is still ubuntu22. Are all available rust image based on ubuntu22?
![Uploading build.PNG…]()

2023-09-28 03:56 UTC, songzhouran commented
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM rust:1.20.0
1.20.0: Pulling from library/rust
3e17c6eae66c: Pull complete 
74d44b20f851: Pull complete 
a156217f3fa4: Pull complete 
4a1ed13b6faa: Pull complete 
c6defea3d225: Pull complete 
e2bfce1bb665: Pull complete 
Digest: sha256:92544708124a7568afe04b2cf1c9c35f781a700ecb9affd2c36c50d08c63bd81
Status: Downloaded newer image for rust:1.20.0
 ---> 78e857abc533
Step 2/3 : LABEL maintainer="Trust"
 ---> Running in 114e4a51d8f5
Removing intermediate container 114e4a51d8f5
 ---> 9000fc6738a9
Step 3/3 : RUN cat /proc/version
 ---> Running in 9d79035648f7
Linux version 5.15.0-82-generic (buildd@lcy02-amd64-027) (gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #91-Ubuntu SMP Mon Aug 14 14:14:14 UTC 2023
Removing intermediate container 9d79035648f7
 ---> d47b42b225a2
Successfully built d47b42b225a2

2023-09-29 08:19 UTC, closed without merging

2023-09-29 08:19 UTC, Kailai-Wang commented
superseded by #2170