Fix: Add worker tag input
litentry/litentry-parachain pull request #2307
Opened 2023-12-05 02:49 UTC by Verin1005

### Context

Previously, when using Docker images, the worker and parachain used the same tag consistently. It's necessary to separate them now, as otherwise, errors similar to those discussed in [Slack](https://litentry.slack.com/archives/C05328L0GAF/p1701704472234529) will occur.

2023-12-05 08:56 UTC, Kailai-Wang requested changes

2023-12-05 08:56 UTC, Kailai-Wang commented on .github/workflows/release-ts-api-package.yml
> +          docker pull litentry/litentry-parachain:${{ inputs.parachain-tag }}
I assume you haven't carefully verified it. This will not work.

Later you have
```
docker compose -f docker-compose.yml -f lit-ts-api-package-build.yml up --no-build --exit-code-from lit-ts-api-package-build lit-ts-api-package-build
```
but `docker-compose.yml` is hardcoded with `latest` tags all over the place.

So you basically pulled the images but they are never used.
Same applies to the `generate_parachain_artefacts.sh` step

2023-12-05 08:58 UTC, Kailai-Wang commented on .github/workflows/release-ts-api-package.yml
> +          docker pull litentry/litentry-parachain:${{ inputs.parachain-tag }}
I think an easy solution is to (re)tag them locally with `docker tag`

2023-12-05 10:02 UTC, Verin1005 commented on .github/workflows/release-ts-api-package.yml
> +          docker pull litentry/litentry-parachain:${{ inputs.parachain-tag }}
Thank you. I have re-tagged the image, and by looking at [docker images --all](https://github.com/litentry/litentry-parachain/actions/runs/7098761623/job/19321757527), we can see that `latest` points to `v0.9.17-1`.

2023-12-05 15:07 UTC, Verin1005 commented
Waiting for P-330 to finish together.

2023-12-06 16:25 UTC, Kailai-Wang approved these changes
Looks good, thanks!
It doesn't work (yet) as we don't build tee-worker images when releasing

2023-12-07 03:09 UTC, Verin1005 commented
> Looks good, thanks! It doesn't work (yet) as we don't build tee-worker images when releasing

see https://github.com/litentry/litentry-parachain/pull/2313

2023-12-07 03:09 UTC, merged