P 345 precompile contract tests
litentry/litentry-parachain pull request #2325
Opened 2023-12-12 13:04 UTC by Traf333

### Context
this PR tends to add integration tests for [Parachain Precompile Contract](https://www.notion.so/web3builders/Parachain-Precompile-Contract-0c34929e5f16408084446dcf3dd36006)

2023-12-13 10:23 UTC, wangminqi commented
https://www.notion.so/web3builders/Litentry-About-user-address-transfer-aeff8bba49054c3cb0204f0b544346ee
We just decided to change mapping address method. For your reference.
Once P-351 passed, some new logic will be applied.

2023-12-15 13:51 UTC, Traf333 commented on ts-tests/tests/precompile-contract.test.ts
> +    // once we add ability to customise minimum waiting time for `executeDelegationRequest` implement tests for the rest functions
Created dedicated task for that [P-360 : Add the rest tests for missing functions](https://linear.app/litentry/issue/P-360/add-the-rest-tests-for-missing-functions)

2023-12-15 18:23 UTC, Kailai-Wang requested changes

2023-12-15 18:23 UTC, Kailai-Wang commented on ts-tests/precompile/contracts/bridge.json
Could you please also add a README under `ts-tests/precompile/` to specify how these JSON files are generated? 

I assume they are not manually generated

2023-12-15 18:23 UTC, Kailai-Wang commented on ts-tests/tests/precompile-contract.test.ts
I don't think this is actually run in CI 😂 

You'll need to change `run-ts-test.sh` and `Makefile` probably

2023-12-18 10:09 UTC, Traf333 commented on ts-tests/tests/precompile-contract.test.ts
I just updated `run-ts-test.sh` and include the tests only for the `evm` flag enabled. Tests are included to CI now. Thanks fro catching it 🙏

2023-12-18 10:11 UTC, Traf333 commented on ts-tests/precompile/contracts/bridge.json
put some brief info about Remix and links to our contracts. Let me know if I need to add more details

2023-12-18 10:20 UTC, Kailai-Wang approved these changes
Looks good to me!

2023-12-18 10:40 UTC, merged

2023-12-20 07:22 UTC, Verin1005 commented on ts-tests/precompile/contracts/bridge.json
Actually, it can also be generated by code. However, Remix is a more convenient way. That day, for the sake of speed, I just used Remix. :p