Fix build error while attesteer feature enabled
litentry/litentry-parachain pull request #2407
Opened 2024-01-16 07:56 UTC by zhouhuitian

build worker with command:

```shell
WORKER_FEATURES=attesteer make
```

Got error:
```shell
error[E0433]: failed to resolve: use of undeclared crate or module `prometheus_metrics`
   --> service/src/main_impl.rs:940:15
    |
940 |     let events = prometheus_metrics::fetch_marblerun_events(marblerun_base_url)
    |                  ^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `prometheus_metrics`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `litentry-worker` due to previous error
```

2024-01-16 08:48 UTC, kziemianek approved these changes

2024-01-16 20:17 UTC, Kailai-Wang requested changes
Although it's a simple change, I'm still being pedantic here

2024-01-16 20:17 UTC, Kailai-Wang commented on tee-worker/service/src/main_impl.rs
> +
IMO we should directly change
```
	let events = prometheus_metrics::fetch_marblerun_events(marblerun_base_url)
```

to 

```
	let events = crate::prometheus_metrics::fetch_marblerun_events(marblerun_base_url)
```

`mod prometheus_metrics` isn't guarded by feature, we shouldn't do that either in the derived file

2024-01-17 10:31 UTC, BillyWooo approved these changes

2024-01-21 22:06 UTC, Kailai-Wang approved these changes

2024-01-22 03:04 UTC, merged