fix: remove fees for TEE callback extrinsics
litentry/litentry-parachain pull request #2533
Opened 2024-02-28 05:28 UTC by felixfaisal

This is a straightforward PR. We observed an `out of balance` for TEE-worker in one of our latest deployment. I went through three pallets namely `teebag` , `identity-management` and `vc-management`. I found two extrinsics in `teebag` that are not feeless and most likely the reason why we observed an `out of balance`. However I'm confused about `post-opaque-task` extrinsic, Are we actively using it or is there an update to it?

2024-02-28 07:40 UTC, Kailai-Wang requested changes

2024-02-28 07:40 UTC, Kailai-Wang commented on pallets/teebag/src/lib.rs
> +			Ok(Pays::No.into())
I don't think this is needed because of `#[pallet::weight((195_000_000, DispatchClass::Normal, Pays::No))]` in line 535, although this might be the preferred way.

The actual problem comes from the `pallet-identity-management` and `pallet-vc-management`, please double check it there.

See the issue description:
> Pallets to check:
> - teebag
> - identity-management
> - vc-management

2024-02-28 08:05 UTC, felixfaisal commented on pallets/teebag/src/lib.rs
> +			Ok(Pays::No.into())
I think i missed out on this detail, I checked both identity-management and vc-management, All the extrinsics created to be called by the tee-worker, are `Pays::No`.

2024-03-04 07:54 UTC, Kailai-Wang approved these changes
Thanks!

2024-03-04 07:57 UTC, kziemianek approved these changes

2024-03-04 18:22 UTC, merged