Remove filter, and enable tests
litentry/litentry-parachain pull request #257
Opened 2021-11-26 16:05 UTC by h4n0

This PR solves issue #243 . 

The runtime filter has been removed on the dev branch. At the same time, previous functional ts tests are activated. A new test type "release test" has been added for filter tests. 

For the later release, we shall add the runtime filter back before each release, and run `make test-release-ci-docker ` to verify if the filter has been correctly added. See [here](https://github.com/litentry/litentry-parachain/commit/e97461a4d2d30e3c1a7adb10d88c24254599b8f8#diff-0ec06ea58bd455f09ce6b3bb4c2c1c0d37bda51c1e1be2151c560c9c973959ec) for details how filter can be added.

2021-11-26 16:26 UTC, Kailai-Wang requested changes
I think we are still missing GitHub Action integration here, either `build_and_run_test.yml` or `create_releease_draft.yml` needs to be modified to actually include the base-filter test, and it should be triggered on release branch only.

2021-11-26 16:26 UTC, Kailai-Wang commented on ts-tests/package.json
> +    "test": "mocha --exit --sort -r ts-node/register 'tests/**/*.test.ts'",
I believe here `base-filter.test.ts` will also be tested for dev branch, which might be unexpected.

2021-11-26 16:26 UTC, Kailai-Wang commented on Makefile
> +	@./scripts/run-ci-test.sh -release
I'd prefer to use `release` here, hyphen might cause some parsing problems on some systems.
Later in `run-ci-test.sh` something like:
```
TYPE=
[ ! -z "$1" ] && TYPE="-$1"
```

2021-11-30 09:24 UTC, closed without merging

2021-11-30 09:24 UTC, h4n0 commented
We decide to keep the BaseCallFilter on. Therefore this PR has to be closed.

Details about our new branch rules: https://www.notion.so/litentry/Parachain-GitHub-Repo-Rules-40c2c5c19b3e4f1990b6d19b9453e9f0