Sol Balance VC with an abort strategy example implementation
litentry/litentry-parachain pull request #2572
Opened 2024-03-13 05:26 UTC by higherordertech

### Context

### Labels

Please apply following PR-related labels when appropriate:
- `C0-breaking`: if your change could break the existing client, e.g. API change, critical logic change 
- `C1-noteworthy`: if your change is non-breaking, but is still worth noticing for the client, e.g. reference code improvement

### How (Optional)

### Testing Evidences

Please attach any relevant evidences if applicable

2024-03-13 15:31 UTC, jonalvarezz commented on tee-worker/litentry/core/common/src/abort_strategy.rs
> +					return Ok(false)
nitpick: should we pass an optional named struct for better readability? i.e. `return Ok(LoopControls.Break)`

2024-03-13 22:01 UTC, BillyWooo reviewed
In general, it looks very good. I left two small comments. The main idea is to introduce the less env variable the better.

2024-03-13 22:01 UTC, BillyWooo commented on bitacross-worker/docker/docker-compose.yml
> +      - MORALIS_SOLANA_API_URL=http://localhost:19527/moralis_solana/
Can we just use `MORALIS_API_URL` ? Add the extra part with code?

2024-03-13 22:01 UTC, BillyWooo commented on tee-worker/litentry/core/data-providers/src/lib.rs
> +			if let Ok(v) = env::var("MORALIS_SOLANA_API_URL") {
These two branches can be merged together.

2024-03-14 23:50 UTC, Kailai-Wang approved these changes
I only checked the `AbortStrategy` impl part, looks good!

2024-03-18 19:12 UTC, BillyWooo requested changes
If there is no strong reason, I still insist to `MORALIS_SOLANA_API_URL`.

2024-03-19 02:13 UTC, higherordertech commented on bitacross-worker/docker/docker-compose.yml
> +      - MORALIS_SOLANA_API_URL=http://localhost:19527/moralis_solana/
moralis_api_url is totally different from moralis_solana_api_url, I think this way is better than merging them together
moralis_api_url: "https://deep-index.moralis.io/api/v2.2/".to_string(),
moralis_solana_api_url: "https://solana-gateway.moralis.io/".to_string(),

2024-03-19 02:14 UTC, higherordertech commented on tee-worker/litentry/core/data-providers/src/lib.rs
> +			if let Ok(v) = env::var("MORALIS_SOLANA_API_URL") {
same as above, not worth merging them

2024-03-19 02:15 UTC, higherordertech commented on tee-worker/litentry/core/common/src/abort_strategy.rs
> +					return Ok(false)
resolved now

2024-03-19 08:18 UTC, BillyWooo approved these changes

2024-03-19 08:18 UTC, merged