Add ws support for DI server
litentry/litentry-parachain pull request #2604
Opened 2024-03-20 09:42 UTC by Kailai-Wang

### Context

As topic. It defines a `MaybeServerTlsStream` struct to wrap up the plain and rustls stream.

Whether launching a ws or wss server will depend on the value of command line arg `--trusted-external-address` or `--T`. Although it's called "external", I reckon it makes little sense when launching an "external" wss server while expecting a ws connection internally in our case. If this value is not present, `wss` will be used as fallback.

Similarly, `--untrusted-external-address` will fallback to `ws`.

Now CI uses `ws` by default.

I can see a potential refactoring of URL management, e.g. use `Url` by default, better stucture of "internal" and "external" addresses - but it's out of scope of this PR.

2024-03-20 09:43 UTC, Kailai-Wang commented
cc @BillyWooo @felixfaisal - once merged and deployed, we need to review the `-T` setting

2024-03-21 11:33 UTC, kziemianek approved these changes

2024-03-21 11:40 UTC, kziemianek requested changes
Should we adjust usage of cli ?

Looks like it `link_identity` fails after this change


```
kziemianek@kziemianek:~/projects/litentry/litentry-parachain/tee-worker/bin$ ./litentry-cli trusted -d link-identity did:litentry:substrate:0x8eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a48 did:litentry:evm:0x0D9bFD1f18f5f4FD08247DC54aD3528909c4b3E9 bsc,ethereum
[2024-03-21T11:34:53.433Z ERROR ws::handler] WS Error <Io(Custom { kind: Other, error: "unexpected EOF" })>
thread 'main' panicked at 'Unable to retrieve MRENCLAVE from endpoint: MspcReceiver(RecvError)', cli/src/trusted_command_utils.rs:88:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

2024-03-21 12:24 UTC, Kailai-Wang commented
> Should we adjust usage of cli ?
> 
> Looks like `link_identity` fails after this change
> 
> ```
> kziemianek@kziemianek:~/projects/litentry/litentry-parachain/tee-worker/bin$ ./litentry-cli trusted -d link-identity did:litentry:substrate:0x8eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a48 did:litentry:evm:0x0D9bFD1f18f5f4FD08247DC54aD3528909c4b3E9 bsc,ethereum
> [2024-03-21T11:34:53.433Z ERROR ws::handler] WS Error <Io(Custom { kind: Other, error: "unexpected EOF" })>
> thread 'main' panicked at 'Unable to retrieve MRENCLAVE from endpoint: MspcReceiver(RecvError)', cli/src/trusted_command_utils.rs:88:14
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

Thanks!
Now the CLI should use ws by default

2024-03-21 12:25 UTC, kziemianek approved these changes

2024-03-21 13:52 UTC, merged