Modify release-ts-api gha
litentry/litentry-parachain pull request #2760
Opened 2024-05-27 11:29 UTC by 0xverin

### Context

After migrating client-api to npm registry and using built worker image directly for deployment, basic modifications need to be made to this gha.

2024-05-27 17:26 UTC, Traf333 commented on .github/workflows/release-ts-api-package.yml
> +          docker tag litentry/litentry-parachain:$DOCKER_TAG litentry/litentry-parachain:latest
these changes might be adjusted once we[ resolve polling ](https://litentry.slack.com/archives/C05328L0GAF/p1716829164458979)

2024-05-28 12:26 UTC, Traf333 requested changes
I'm not sure that even after merging [the PR](https://github.com/litentry/litentry-parachain/pull/2759), your changes would work. From what I understood, we don't have `litentry/identity-cli`, but you can extract it from `litentry/identity-worker` 

@Kailai-Wang can you correct me if I'm wrong?

2024-05-28 13:50 UTC, 0xverin commented
> I'm not sure that even after merging [the PR](https://github.com/litentry/litentry-parachain/pull/2759), your changes would work. From what I understood, we don't have `litentry/identity-cli`, but you can extract it from `litentry/identity-worker`
> 
> @Kailai-Wang can you correct me if I'm wrong?

I saw `identity-cli` on Docker Hub when I was making modifications.
https://hub.docker.com/r/litentry/identity-cli

2024-05-28 14:03 UTC, Traf333 commented
Oh, my bad. It was addressed within this PR https://github.com/litentry/litentry-parachain/pull/2761

2024-05-28 14:03 UTC, Traf333 approved these changes
🚀

2024-05-28 14:41 UTC, merged