client-api: update sidechain and parachain publish steps
litentry/litentry-parachain pull request #2806
Opened 2024-06-12 19:51 UTC by jonalvarezz

Move the version bump step as first step so that published package includes the latest `package.json` file.

2024-06-12 19:52 UTC, jonalvarezz commented on tee-worker/client-api/.prettierrc
> +  "singleQuote": false
opportunistic change: I noticed that there is some mix between single and double quotes. The former seems predominates. Made it explicit in prettier.

2024-06-17 13:57 UTC, 0xverin requested changes

2024-06-17 13:57 UTC, 0xverin commented on tee-worker/client-api/sidechain-api/README.md
> +    Use `next` tag for preview versions. Use `latest` tag for
Should be consistent with the parachain-api? Also, it seems that the description is missing?

2024-06-17 14:55 UTC, jonalvarezz commented on tee-worker/client-api/sidechain-api/README.md
> +    Use `next` tag for preview versions. Use `latest` tag for
Thanks! I cherry-picked and this one was left behind 😄
I added it manually. both readme are consistent

2024-06-17 15:21 UTC, 0xverin approved these changes

2024-06-17 15:27 UTC, merged