chrome: remove all solidity contract codes
litentry/litentry-parachain pull request #3073
Opened 2024-09-18 05:06 UTC by higherordertech

### Context

### Labels

Please apply following PR-related labels when appropriate:
- `C0-breaking`: if your change could break the existing client, e.g. API change, critical logic change 
- `C1-noteworthy`: if your change is non-breaking, but is still worth noticing for the client, e.g. reference code improvement

### How (Optional)

### Testing Evidences

Please attach any relevant evidences if applicable

2024-09-18 07:48 UTC, 0xverin approved these changes
Thanks!

2024-09-18 09:17 UTC, BillyWooo commented
@higherordertech Please also remove the test within ci.yml.

2024-09-18 09:18 UTC, BillyWooo commented
for the record: https://github.com/litentry/DynamicAssertion/pull/5

2024-09-18 09:21 UTC, BillyWooo requested changes
@higherordertech Please also remove the test within ci.yml.

2024-09-19 00:24 UTC, higherordertech commented on .github/workflows/ci.yml
@BillyWooo anything else to delete in this ci.yml?

2024-09-20 13:20 UTC, BillyWooo commented on .github/workflows/ci.yml
@higherordertech "lit-assertion-contracts-test", please check the CI status of this PR.

2024-09-23 03:16 UTC, higherordertech commented on .github/workflows/ci.yml
lit-assertion-contracts-test already deleted in this PR.

The CI status is from dev branch.

https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request

This event runs in the context of the base of the pull request, rather than in the context of the merge commit, as the event does. This prevents execution of unsafe code from the head of the pull request that could alter your repository or steal any secrets you use in your workflow. This event allows your workflow to do things like label or comment on pull requests from forks. Avoid using this event if you need to build or run code from the pull request.

![image](https://github.com/user-attachments/assets/bbc4d49f-4599-410e-a8f8-77bbc1888b3c)

2024-09-23 03:46 UTC, higherordertech commented on .github/workflows/ci.yml
Seperated PR to remove the Ci job lit-assertion-contracts-test first: https://github.com/litentry/litentry-parachain/pull/3081

2024-09-25 09:40 UTC, closed without merging