Ajustment to baseCallFilters
litentry/litentry-parachain pull request #640
Opened 2022-06-13 09:22 UTC by Kailai-Wang

resolves #635 
resolves #637 

This PR:
- explicitly allows core calls in any case
- add integration test for baseCallFilters
- refactor transaction_payment integration-test to remove magic numbers
- activate XTokens

2022-06-13 11:19 UTC, Kailai-Wang commented
I'd need your review too @wangminqi , especially the transaction_payment part

2022-06-14 02:14 UTC, wangminqi requested changes

2022-06-14 02:14 UTC, wangminqi commented on runtime/litentry/src/lib.rs
> +		false
Just to confirm, we deliberate make Safe and Normal Mode Filter same?

2022-06-14 02:14 UTC, wangminqi commented on runtime/litmus/src/tests/base_call_filter.rs
> +
I suggest we have an extra test that root call bypasses the filter (just in case of future upstream change)

2022-06-14 02:32 UTC, wangminqi approved these changes

2022-06-14 02:33 UTC, wangminqi commented
I suggest we have an extra unittest that root call bypass the filter. But that will be a light issue.

2022-06-14 07:38 UTC, Kailai-Wang commented
> I suggest we have an extra unittest that root call bypass the filter. But that will be a light issue.

I believe `sudo` pallet unittest should already cover that, see
https://github.com/paritytech/substrate/blob/9a140a6190ae1527b89fe77bd426a38489526e44/frame/sudo/src/mock.rs#L115-L120

and the sudo calls in tests.rs still pass

2022-06-14 07:57 UTC, merged

2022-06-14 08:26 UTC, wangminqi commented
I mean, something not through sudo, just trigger through origin::root(), like schedule does after democracy. But should be similar. I guess it is fine.

2022-06-14 08:58 UTC, Kailai-Wang commented
> I mean, something not through sudo, just trigger through origin::root(), like schedule does after democracy. But should be similar. I guess it is fine.

You're probably talking about `call.dispatch(Origin::root())`, IMO the unittest should be again be covered by substrate, in frame_system for example. If you actually mean integration-test, yea that should be trivial/similar to the unittest body in substrate, but let me add another testcase in the next PR together with 0.9.23 update

2022-06-15 19:32 UTC, Kailai-Wang commented
@wangminqi
testcase was added in #649