Orml xcm impl
litentry/litentry-parachain pull request #792
Opened 2022-08-31 07:05 UTC by Jinsipang

orml_xcm reference implementation

2022-08-31 08:31 UTC, Kailai-Wang commented
- This branch is out-of-date with the base branch
- Do we have an issue with it? What's the background of this PR?

2022-08-31 08:57 UTC, Jinsipang commented
The relate issue link https://github.com/litentry/litentry-parachain/issues/725

2022-08-31 19:56 UTC, Kailai-Wang commented
> The relate issue link #725

Thanks, let's use the [github keywords](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) to refer to the issue link in the PR description so that the issue can get closed when the PR is merged.

2022-09-01 05:58 UTC, wangminqi requested changes

2022-09-01 05:58 UTC, wangminqi commented on runtime/common/src/tests/orml_xcm.rs
> +		+ std::convert::From<
This restriction is suspicious. Please check and feedback the reason for doing so.

2022-09-01 05:58 UTC, wangminqi commented on runtime/common/src/tests/orml_xcm.rs
> +		> + std::fmt::Debug,
same above. fmt restriction is also weird to display in the code.

2022-09-01 05:58 UTC, wangminqi commented on runtime/rococo/src/xcm_config.rs
> +pub struct EnsureXcmOriginWithSpecialRootGroup<Origin, Conversion, SpecialRootGroup>(
Please replace Litentry part to rococo too.

2022-09-02 13:57 UTC, wangminqi approved these changes

2022-09-05 03:19 UTC, merged